[workspace]

members = [
    "rts",
    "rts/cli",
]

exclude = [

]

[profile.dev.package."*"]
opt-level = 2

[profile.dev.build-override]
opt-level = 2

[patch.crates-io]
distill = { git = "https://github.com/amethyst/distill.git", rev = "9e127ca9d034e0c7dffb747f8aae3a2607b0e1e8" }