[package]
name = "rts-lib"
version = "0.1.0"
authors = ["Călin Ardelean <mmn80cpu@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
sled = "0.34.6"
zerocopy = "0.4.0"
byteorder = "1.4.2"
wgpu = "0.7.0"
